### ISSUE TITLE
TODO: list.h

### ISSUE THREAD

**Issue by harsath** [harsath/cap-containers#1]
- [x] `Iterator` for iterating over the linked list.
- [x] `Iterator* cap_list_get_forward_iterator()`
- [ ] `void cap_list_iterator_increment_forward(Iterator*)`
- [ ] `void cap_list_iterator_decrement_forward(Iterator*)`
- [ ] `Iterator* cap_list_get_reverse_iterator()`
- [ ] `void cap_list_iterator_increment_reverse(Iterator*)`
- [ ] `void cap_list_iterator_decrement_reverse(Iterator*)`

**Comment by harsath** [comment]
done
